---
- name: playbook to deploy tomcat
  hosts: all
  become: yes
  vars:
    tomcat_url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.63/bin/apache-tom$
  tasks:
     - name: update instance
       apt:
         update_cache: yes

     - name: install java
       package:
          name: openjdk-8-jdk
          state: present
     - name: download tomcat
       unarchive:
          src:  "{{tomcat_url}}"
          dest: /opt/
          remote_src: yes
     - name: copy war file
       copy:
         src: /var/lib/jenkins/workspace/jenkins_ansible/target/LoginWebApp-1.war
         dest: /opt/apache-tomcat-8.5.63/webapps/
     - name: copying server.xml
       copy:
         src: server.xml
         dest: /opt/apache-tomcat-8.5.63/conf/server.xml
         mode: 0755
         force: yes
     - name: Install Tomcat init script
       copy:
        src: tomcat-initscript.sh
        dest: /etc/init.d/tomcat
        mode: 0755
     - name: reload the web server
       shell: systemctl daemon-reload
     - name: start tomcat
       service:
         name: tomcat
         state: restarted

